debug: false

################## [SERVER] #################
server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /
################## [SPRING] #################
spring:
  main:
    banner-mode: console
    log-startup-info: true
################## [APP] #################
app:
  environment: dev
################## [LOGGING] #################

logging:
  level:
    root: DEBUG
    org.springframework.core.env.PropertySourcesPropertyResolver: TRACE
    org.springframework.boot.context.config.ConfigFileApplicationListener: DEBUG
    com.application.web: DEBUG
    org:
      hibernate:
        SQL: WARN
      springframework:
        security: DEBUG